### ISSUE TITLE
Cannot delete a hierarchical relationship that has been defined in a project for an external namespace

### ISSUE THREAD

**Issue by iltzortz** [geovistory/ontome#125]
**Describe the bug**
I managed to create a hierarchical relationship for an external referenced namespace which is wrong and i cannot delete. It does not seem to affect the external namespace but it is present in the rdfs export and needs to be removed

**To Reproduce**
1. Create a class e.g. with id TX2 Writing
2. Go to hierarchy tab and define a superclass from crm base e.g. E36 Visual Item
3. E36 Visual Item will appear in the list of parent classes. If you click on E36 Visual Item then the interface will allow you to add a parent class to E36 Visual Item. 
4. I add as parent class the E37 Mark (which is wrong as it creates a cycle - E37 is subclass of E36 not the opposite) and although nothing seems to be affected there has actually been created such a relationship in my namespace which is exported with rdfs generation and i cannot delete.

**Expected behavior**
- I think i should not be able to add a parent class to an external namespace - if i should be able to do so then the 1st image should actually display some success message
- I should be able to delete the hierarchical relationship that has been created for the external namespace in the only tab that it appears in the interface (in the relations tab) via a delete option. Otherwise it will always be included in my export rdfs file
[namespace-CRMtex ongoing (1).rdf.txt](https://github.com/geovistory/ontome/files/13864035/namespace-CRMtex.ongoing.1.rdf.txt)

![image](https://github.com/geovistory/ontome/assets/8971147/f20bc010-15b0-46aa-afa4-77d23580b546)

![image](https://github.com/geovistory/ontome/assets/8971147/ac485315-6eef-49e8-bce6-870754b69669)

**Comment by valamercery** [comment]
Thanks for submitting this issue. After checking, it turns out that there is no bug.

For some strange reason, CRMtex appears to be unchecked in your "My current namespaces" tab of your dashboard. Add it or click on reset and you'll see the hierarchical relationship appear with the delete button on the E36 Visual Item page.
But you're right, it might be a good idea to add an edit/delete button to the list of relations. As it will be a new feature, I invite you to open a [discussion](https://github.com/orgs/geovistory/discussions) on this subject if you wish.

Otherwise we feel it is appropriate to allow the addition of a hierarchical relationship defined in a namespace between two classes which do not belong to this namespace. This relationship will only appear if the namespace in which it is defined is selected, and will only be exported in the serialization of this namespace.
